### ISSUE TITLE
云开发控制台打不开

### ISSUE THREAD

**Issue by RobiNexy** [msojocs/wechat-devtools-linux#9]
点击云开发按钮显示 Uncaught TypeError:Cannot read property 'isDev' of undefined

**Comment by msojocs** [comment]
正在尝试处理
![image](https://user-images.githubusercontent.com/20937135/152486161-fb4b20d3-b580-4fbf-9bc8-397274f0c36c.png)

**Comment by msojocs** [comment]
初步处理完毕，由于我没使用过云开发，所以有些问题可能发现不了。

**Comment by msojocs** [comment]
似乎没有问题，就先关闭了。
